# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "544abe90d16982e9f853e323ab77e7c5"
application_url = "https://graw-ai-chatbot-vilros-v2.fly.dev"
embedded = true
name = "GRAW AI - (Vilros v2)"
handle = "graw-ai-chatbot-vilros-v2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://graw-ai-chatbot-vilros-v2.fly.dev/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://graw-ai-chatbot-vilros-v2.fly.dev/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "https://graw-ai-chatbot-vilros-v2.fly.dev/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_pixels,read_pixels,read_customer_events,read_orders"

[auth]
redirect_urls = [
  "https://graw-ai-chatbot-vilros-v2.fly.dev/auth/callback",
  "https://graw-ai-chatbot-vilros-v2.fly.dev/auth/shopify/callback",
  "https://graw-ai-chatbot-vilros-v2.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://graw-ai-chatbot-vilros-v2.fly.dev/api/voiceflow"
subpath = "voiceflow"
prefix = "apps"

[pos]
embedded = false
